### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by hendrykeren** [arjunsk/Ionic-XMPP-Chat-Client-with-SQL#2]
Hello sir.
You have a great app, unfortunately this app does not have a logo yet, may I donate a logo for your app?

**Comment by autoincr** [comment]
I was more focusing towards the functionality. Feel free to contribute the logo.

**Comment by hendrykeren** [comment]
I intend to donate the logo for your project, I will make it as soon as possible and send notification to this issue
